# This file was generated by GoReleaser. DO NOT EDIT.
cask "speakeasy" do
  desc ""
  homepage ""
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "speakeasy"

  on_macos do
    on_intel do
      url "https://github.com/ninoseki/speakeasy/releases/download/v0.0.1/speakeasy_Darwin_x86_64.tar.gz"
      sha256 "84f0b6124ea849d1f180e3150455dedf45ee18f2661ea81f1f2c6391d6ea8449"
    end
    on_arm do
      url "https://github.com/ninoseki/speakeasy/releases/download/v0.0.1/speakeasy_Darwin_arm64.tar.gz"
      sha256 "88b51d262b050102b6ed155e1ef768ddc812dcd8f3af409e44c80215c8fff96c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ninoseki/speakeasy/releases/download/v0.0.1/speakeasy_Linux_x86_64.tar.gz"
      sha256 "89d5cb72fe8bac6b7d1b124aa135be2fc0fec3e24d8a47c4b311c512f91e6f43"
    end
    on_arm do
      url "https://github.com/ninoseki/speakeasy/releases/download/v0.0.1/speakeasy_Linux_arm64.tar.gz"
      sha256 "abef2305b7687bca5604ffff314fefdaf138e25701cd4e1e11c0913ff12d24f1"
    end
  end

  # No zap stanza required
end
